### ISSUE TITLE
Add sorted built-in

### ISSUE THREAD

**Issue by hniksic** [maxfischer2781/asyncstdlib#18]
The `sorted` built-in seems like it would come useful:

```python
sorted_items = await sorted(my_aiter, key=my_key)
```

If it's omitted intentionally, feel free to reject this issue.

**Comment by maxfischer2781** [comment]
I have not yet considered ``sorted`` to be honest. Would welcome some food for thought.

My rule of thumb so far is to include only parts that benefit from being internally ``async`` – for example, ``max`` benefits from evaluating the key/iterable for each item and throwing it away immediately if smaller than the current. Since the result of ``sorted`` needs *all* values and *all* keys, there is little technical advantage versus externally creating the list-and-keys to sort and feeding them to ``builtins.sorted``.

I am mainly looking to avoid giving a false promise of concurrency – the "obvious" feature would be to evaluate all keys concurrently at once, which ``asyncstdlib`` cannot do (as it is not aware of the actual event loop library). Is that what crosses your mind when you say "seems like it would come useful"?

Then again the *other* goal is to avoid people building their own, half-baked tools. A quick draft shows that "creating the list-and-keys to sort and feeding them to ``builtins.sorted``" is rather ugly, with some sharp edges. So I am indeed slightly in favour of adding ``sorted`` unless it seems too promising.
