### ISSUE TITLE
Question regarding awaitables

### ISSUE THREAD

**Issue by mristin** [maxfischer2781/asyncstdlib#27]
Hi @maxfischer2781 ,
First of all, thanks for developing asyncstdlib!

I am writing [icontract](https://github.com/Parquery/icontract), a library for design-by-contract in Python. As Python 3 lacks the support for async lambdas (see the [Python issue 33447](https://bugs.python.org/issue33447)) I am searching for a workaround so that contracts can still be defined as lambda functions. Instead of a concrete (realized) value, the lambda returns a coroutine. I am wondering whether asyncstdlib can fit the bill? 

I played with it in the console, but couldn't really figure out how to achieve what I need. Here is a short code snippet defining functions that I'd need:
```python
T = TypeVar('T')

async def awaited_all(aws: Iterable[Awaitable[T]]) -> bool:
    """Await each item in ``aws`` and then check that ``all`` holds."""
    for awaitable in aws:
        if not await awaitable:
            return False

    return True

U = TypeVar('U')
V = TypeVar('V')

async def awaited_to(func: Callable[[U], V], awaitable: Awaitable[U]) -> V:
    """Await the ``awaitable`` and then apply ``func`` on it."""
    return func(await awaitable)
```

As you see, the implementation is quite simple. As far as I understood, the focus of asyncstdlib is on *async iterators* instead of *sync iterators* over *awaitables*, is that correct?

If asyncstdlib can not be used, are you maybe aware of a library that implements the functions that I need?

**Comment by mristin** [comment]
I wrote a proof-of-concept micro-library to see how this functionality can be implemented. This is the current dev branch: https://github.com/mristin/awaited/tree/mristin/Kick-off

Would you like me to move `that` and `these` implementation as a PR to asyncstdlib or should I keep the `awaited` library separate?

**Comment by maxfischer2781** [comment]
This is certainly an interesting use-case. ``asyncstdlib`` is primarily about replicating the standard library -- which is more than *async iterators*, but these are just the most applicable -- but there is ``asyncstdlib.asynctools`` for useful stuff so it could fit.

The ``awaited.these``  function could go straight into ``asyncstdlib.asynctools``, provided it gets a descriptive name.

The ``awaited.then`` looks suspiciously like a [monad combinator/``bind``](https://en.wikipedia.org/wiki/Monad_(functional_programming)#Definition). Fittingly, ``asyncstdlib`` internally uses an (almost) [monad constructor/``unit``](https://github.com/maxfischer2781/asyncstdlib/blob/e9d9cba5c1d4b896b6a11a83a20310d7eaf10fcf/asyncstdlib/_core.py#L87) which I did not make public because it seemed incomplete. I would have to ponder how to best expose that.
(Further reads an async as monads [here](https://gist.github.com/MaiaVictor/bc0c02b6d1fbc7e3dbae838fb1376c80) and [here](https://qr.ae/pNjt25))

--------------

So, the TLDR is: ``awaited.these`` can go right in with a proper name. ``awaited.then`` would need some thinking on the interface.  
I would leave it up to you whether you want to PR ``awaited.these`` in isolation now.

**Comment by maxfischer2781** [comment]
As for existing libraries, ``returns`` provides a [monad for async/sync combinations](https://github.com/dry-python/returns/issues/274). Not sure if that is overkill for your case, since it ships with a lot more functionality.

**Comment by mristin** [comment]
@maxfischer2781 thanks! Any suggestion for a better name for `these`?

I'd prefer to keep dependencies small, so putting both in asyncstdlib would be a great solution for me. I'll put `these` in a PR tonight.

**Comment by mristin** [comment]
@maxfischer2781 I had a quick look at awaitify, but it looks like the behavior is different (it returns a callable instead of the application on the awaited value)?

**Comment by maxfischer2781** [comment]
@mristin I've split of an issue fo ``these`` at #28. Some preliminary name suggestions, but not sure what would work best.

**Comment by maxfischer2781** [comment]
Sorry for being vague about ``then``/``awaitify``; the latter is not a replacement for the former. They are two parts of the same "thing", which is "treat a sync function as async". So I am pondering whether it would be useful and useable making them one thing.

**Comment by mristin** [comment]
No worries -- brain storming is important :).

I would argue against complex implementations. First, because the library like this needs a high level of reliability (simple = "obviously no bugs, rather than no obvious bugs"). Second, this lib aims to be heavily used in many places throughout the system, so a small overhead accumulates and can cause a significant slow down.

**Comment by maxfischer2781** [comment]
Agreed, no point overcomplicating this. Let's trash monads and friends.

---------------

My minimum requirement would be to support arbitrarily many arguments. This would match the old [Python2 apply](https://docs.python.org/2.7/library/functions.html#apply) quite clearly. There is some overlap with ``partial``, but that would be pushing it.
```python3
async def apply(__fnc: Callable[..., R], *args: Awaitable[T], **kwargs: Awaitable[T]) -> R:
    return __fnc(*[await arg for arg in args], **{k: await arg for k, arg in kwargs.items()})
```
That should be fine with a fast-path if there are no ``kwargs``, and possibly even if there is only one ``args``.

---------------

There's one thing left to ponder, though: Are you aiming at *using* or *defining* "async ``lambda``"? The definitions of ``awaited_to``, ``then`` and ``apply`` are one-shot – their ``awaitable``s are consumed on usage via ``await``.

For a hypothetical ``async lambda x, y: x * await y()`` the ``y`` is a ``() -> Awaitable[T]`` instead of just an `Awaitable[T]`. So it would look more like this:
```python3
def alpha(func: Callable[..., R]) -> Callable[..., Awaitable[R]]:
    """`async lambda a, b: await a() * await b()` -> `alpha(lambda a, b: a*b)`"""
    async def call(*args: Callable[[], Awaitable[T]]) -> R:
        return func(*[await arg() for arg in args])
    return call
```
That still won't get 100% `async lambda`: it cannot distinguish between the various forms of ``a``, ``a()``, ``await a`` and ``await a()`` and globals are right out.

**Comment by mristin** [comment]
> There's one thing left to ponder, though: Are you aiming at using or defining "async lambda"?

If I understood your examples correctly, it would be *using* them in my use case.

For example, I need to write contracts that might depend on async functions in [icontract]:

```python
async def check_that_x_is_in_database(x: int) -> bool:
	...

@icontract.require(lambda x: check_that_x_is_in_database(x))
async def some_func(x: int) -> None:
	...
```
[icontract] will internally check if the condition function returned a coroutine. If so, it will first await it, and then check for truthiness. (Otherwise, it immediately checks for truthiness.)

**Comment by mristin** [comment]
@maxfischer2781 let us merge the pull request #29 first, and then I'll make a pull request for `apply`.

Is `apply` the correct name? What about `await_then` to make it similar to `await_each`?

**Comment by mristin** [comment]
Closing since this issue was forked into issues #28 and #33.
