### ISSUE TITLE
clearing cache before it exists raises AttributeError

### ISSUE THREAD

**Issue by skewty** [maxfischer2781/asyncstdlib#93]
Where `self.site_map` is a `@cached_property`, I use the following to work around the issue:
```python
def reset_cache(self) -> None:
    if "site_map" in self.__dict__:
        del self.__dict__["site_map"]
```
Perhaps some checks could be added in the library so this isn't necessary in my code?

FYI Calling `del self.site_map` gives me a PyCharm linter error that I can override with:
 `# noinspection PyPropertyAccess`.

The code above works around both the linter error and the AttributeError issues.

Perhaps providing this alternate approach to clear cache could be provided in the documentation?

The storage of the cached value in `self.__dict__` is an implementation detail that my code shouldn't know about and may change in the future. I am thus of the strong belief that this should be done upstream (in the library) so that this implementation detail need not be coupled in downstream code.

Thanks for the great library. I love it and use it often.

**Comment by skewty** [comment]
Perhaps include some helper functions?

```python
def reset_cached_properties(self) -> None:
    cached_properties = (
        attribute
        for attribute in dir(self.__class__)
        if getattr(self.__class__, attribute).__class__ is cached_property
    )
    for attribute in cached_properties:
        if attribute in self.__dict__:
            del self.__dict__[attribute]
            
class Foo:
    @cached_property
    async def site_map(self) -> dict:
        ...

    def reset_cache(self) -> None:
        reset_cached_properties(self)
```

**Comment by maxfischer2781** [comment]
Thanks for the report. I need to check how the standard library `cached_property` handles this case.

**Comment by maxfischer2781** [comment]
I'm afraid this is the behaviour of the standard library `cached_property` as well. The warnings are a bug of PyCharm (or at least worded misleadingly). So there is nothing to be fixed or added per se.

However, since I wanted to expand the documentation with recipes and such... this seems like something worth documenting. The proper way to handle this is to *try* delete the cache and ignore failure:
```python3
def reset_cache(self) -> None:
    try:
        del self.site_map
    except AttributeError:
        pass
```
This allows safely clearing the cache without making any assumptions beyond it being a non-data descriptor. PyCharm will still complain about this, but there is no way to fix that other than by telling PyCharm that it is wrong.

**Comment by maxfischer2781** [comment]
I didn't find a proper place where to put this in the docs – since this is exactly the same as for the standard library implementation, it seemed out of place. I'm hoping that if anyone else has the issue they will find this one, including the proper way to handle it.
